/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tarefa_A_Recomendacao_Alimentacao;
import java.awt.Dimension;
import java.awt.TextArea;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import org.jpl7.Query;
/**
 *
 * @author Leandro Cunha
 */
public class Recomendacao extends javax.swing.JFrame {
    
    static String resposta;
    static String fastfood;
    static String tipo;
    static String regiao;
    static String preco;
    static String idade;
    
    
    /**
     * Creates new form Recomendacao
     */
    public Recomendacao() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Qual a sua idade?");

        jRadioButton1.setText("Jovem (0-17)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Adulto (18-51)");

        jRadioButton3.setText("Sénior (+51)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Qual a sua região?");

        jRadioButton4.setText("Norte");

        jRadioButton5.setText("Centro");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("Sul");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Qual o tipo de refeição que procura?");

        jRadioButton7.setText("Normal");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("Vegetariano");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Indique o valor que pretende pagar pela refeição.");

        jRadioButton10.setText("<10€");

        jRadioButton11.setText(">10€");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Formulário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel6)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton9))
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String conexao = "consult('alimentacao.pl')";
        Query query = new Query(conexao);
        System.out.println(query.hasSolution() ? "ok" : "erro");
        
        if((jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected()) &&
                (jRadioButton4.isSelected() || jRadioButton5.isSelected() || jRadioButton6.isSelected()) &&
                (jRadioButton7.isSelected() ||jRadioButton9.isSelected()) &&
                (jRadioButton10.isSelected() || jRadioButton11.isSelected())) {
            
            if((((jRadioButton1.isSelected() && jRadioButton2.isSelected() && jRadioButton3.isSelected())) || 
                    (jRadioButton1.isSelected() && jRadioButton2.isSelected()) || 
                    (jRadioButton1.isSelected() && jRadioButton3.isSelected()) ||
                    (jRadioButton2.isSelected() && jRadioButton3.isSelected())) || 
                    (((jRadioButton4.isSelected() && jRadioButton5.isSelected() && jRadioButton6.isSelected())) || 
                    (jRadioButton4.isSelected() && jRadioButton5.isSelected()) || 
                    (jRadioButton4.isSelected() && jRadioButton6.isSelected()) ||
                    (jRadioButton5.isSelected() && jRadioButton6.isSelected())) ||
                    (((jRadioButton7.isSelected() && jRadioButton9.isSelected())) || 
                    (jRadioButton7.isSelected() && jRadioButton9.isSelected())) ||
                    (jRadioButton10.isSelected() && jRadioButton11.isSelected())) {
                
                JOptionPane.showMessageDialog(null, "Selecione apenas uma opção pada cada questão!");
                
            }else {
                
                if(jRadioButton1.isSelected()) {
                    String input = "menor18";
                    this.resposta = "assert(fact("+input+")).";
                     Query query_exec = new Query(resposta);
                     query_exec.oneSolution();
                     this.idade = "menor18";
                }
                
                if(jRadioButton2.isSelected()) {
                    
                    String input = "1850";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.idade = "de18a50";
                }
                
                if(jRadioButton3.isSelected()) {
                    
                    String input = "mais51";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.idade = "mais51";
                }
                
                if(jRadioButton4.isSelected()) {
                    
                    String input = "norte";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.regiao = "norte";
                }
                
                if(jRadioButton5.isSelected()) {
                    
                    String input = "centro";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.regiao = "centro";
                }
                
                if(jRadioButton6.isSelected()) {
                    
                    String input = "sul";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.regiao = "sul";
                }
                
                if(jRadioButton7.isSelected()) {
                    
                    String input = "normal";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.tipo = "normal";
                }
                
                
                
                if(jRadioButton9.isSelected()) {
                    
                    String input = "vegetariano";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.tipo = "vegetariano";
                }
                 
                 
                if(jRadioButton10.isSelected()) {
                    
                    String input = "menor10";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.preco = "menor10";
                }
                
                if(jRadioButton11.isSelected()) {
                    
                    String input = "maior10";
                    this.resposta = "assert(fact("+input+")).";
                    Query query_exec = new Query(resposta);
                    query_exec.oneSolution();
                    this.preco = "maior10";
                }
                
                this.resposta = "res(P).";
                
                System.out.println(resposta);
                            
                Query query_exec = new Query(resposta);
      
                String sugestao = query_exec.oneSolution().get("P").toString();
                
                sugestao = sugestao.replace("[", "");
                sugestao = sugestao.replace("|", "");
                sugestao = sugestao.replace("]", "");
                sugestao = sugestao.replace("(", "");
                sugestao = sugestao.replace("'", "");
                sugestao = sugestao.replace(")", "");
                sugestao = sugestao.replace("_1", "");
                
                //String modificada = sugestao.substring(0, sugestao.length()-2);
                System.out.println(sugestao);
                
                String conexao2 = "consult('refeicaoaconselhamento3.pl')";
                Query query2 = new Query(conexao2);
                System.out.println(query2.hasSolution() ? "ok" : "erro");

                //Verifica qual o q. que tem de chamar para devolver a resposta "yes" ou "no" quanto ao fastfood
                
                
                String teste = "";
                teste = "learn_rules.";
                Query query_exec2 = new Query(teste);
                query_exec2.oneSolution();
                    
                String query1 = "q1(C,"+this.tipo+","+this.idade + "," + this.regiao + "," + this.preco + ").";
                Query query_exec3 = new Query(query1);
                this.fastfood = query_exec3.oneSolution().get("C").toString();
                   
                
                System.out.println(this.fastfood);
                
               if(this.fastfood.equals("yes")) {
                    this.fastfood = "sim";
                }else {
                    this.fastfood = "não";
                }
               
                
                Resultado res = new Resultado(sugestao, this.fastfood);
                res.setVisible(true);
                res.setLocationRelativeTo(null);
                this.dispose();
               
                                
            }
            
            
        }else {
            JOptionPane.showMessageDialog(null, "Deve selecionar uma das opções!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recomendacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recomendacao().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
